### ISSUE TITLE
Using action with local repo

### ISSUE THREAD

**Issue by chinmay-kothari** [andstor/jsdoc-action#25]
Hi,

I want to use jsdoc-action to generate a github page with my [local repo](http//github.com/chinmay-kothari/bookbrainz-site). I have previously used the action with my other repo and I am really impressed with it.

.yml file: https://github.com/chinmay-kothari/bookbrainz-site/blob/master/.github/workflows/documentation.yml

conf.json: https://github.com/chinmay-kothari/bookbrainz-site/blob/master/conf.json

Can you provide any help on where I might be going wrong here? Thanks!

**Comment by andstor** [comment]
Hi,
glad you like this action 😄 

You do not seem to have any problem with the action setup. However, your problem is that you make use of [Flow](https://flow.org). [JSDoc](https://github.com/jsdoc/jsdoc) do not support Flow, and this results in an error.

In order to solve your problem, you have several options available. It seems that you already provide JSDoc for most of the code. You could therefore just completely remove Flow altogether. However, if you really need Flow, you could include a workflow step for stripping all Flow types just before generating the JSDoc. See for example [@babel/plugin-transform-flow-strip-types](https://babeljs.io/docs/en/babel-plugin-transform-flow-strip-types). I tested it locally, and it works like a dream 😉

**Comment by chinmay-kothari** [comment]
Can you help me with the exact step that I would be needing, I have no prior experience of writing github action. 

Would this step work:
`- name: Strip flow type`
    ` uses: babel/plugin-transform-flow-strip-types`

**Comment by chinmay-kothari** [comment]
> Can you help me with the exact step that I would be needing, I have no prior experience of writing github action.
> 
> Would this step work:
> `- name: Strip flow type`
> ` uses: babel/plugin-transform-flow-strip-types`

@andstor Can you help me with this?

**Comment by andstor** [comment]
Sorry, but I am currently very busy so I'm not able to guide you through this at the moment 😅

However, I would recommend to ask this question on [Stack Overflow](https://stackoverflow.com). I'm sure someone can help you there. Tag it with `github-actions`.
