### ISSUE TITLE
Output folder created, but nothing shows up in the repo after workflow finishes

### ISSUE THREAD

**Issue by IntelBear** [andstor/jsdoc-action#29]
Hello, I set up a simple GitHub repo with a Javascript file that I'm using to test out your tool, and I'm having an issue with no output showing up in the repo afterward. I'm following the example you provided, omitting the deployment section

Unless I'm misunderstanding something, I'm assuming it will save the result in the repo with the output_dir given.

If I did misunderstand and its not intended to save the results to the GitHub repo itself, would you happen to know a way of saving it to master without needing to manually upload a saved artifact?

**Comment by IntelBear** [comment]
I've verified that within the workflow, everything is working as intended, the output-dir contains the files I'm expecting

**Comment by andstor** [comment]
The JSDoc Action generates the documentation files and places them to the specified output directory. However, these files only exist inside the VM for the running workflow. normally, you would deploy these files somewhere. In order to store the generated files back to your repo, you need to add a separate step where you add, commit and push the changes.

I took a look at your [repo](https://github.com/IntelBear/CSE-110-Lab-2), and it seems that you have figured this out already. I am therefore closing this for now. Please don't hesitate to reopen if you encounter more problems.
